// <auto-generated />
namespace KURSACH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Linkfromstudenttolabsandabs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Linkfromstudenttolabsandabs));
        
        string IMigrationMetadata.Id
        {
            get { return "201709061823224_Link from student to labs and abs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
